name = "Unofficial Quilt SMP"
author = "woodiertexas"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7be5c716fccc0f758ccfbe9ba81f578764a966576af94fc9763a7fcd72a04e61"

[versions]
minecraft = "1.20.1"
quilt = "0.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
