name = "Unofficial Quilt SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12ff7fe8954092dcaa77c1baceaf1aba3fc542b94fcd65cef907402ec2c2cb5b"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
