name = "Debuggy SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b39532f55160f19a8c730fcaae82b7f3cc980cd18b67407b15689a25530ff7c0"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
