name = "Debuggy SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f0cc974d0159b116812f7515d4c50e8d4f5298ac86bf03c47b2060a372eaa0f"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
