name = "Unofficial Quilt SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c519ef29a4ec67a14122ad8f3821bbc5a45da2313712b7a675fc485f3dcac27b"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
