name = "Debuggy SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26319ed5410da5850b5179e17b74ba5f59f9230833fa321efd676626f884441d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
