name = "Unofficial Quilt SMP"
author = "woodiertexas"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c9c1691ccae68bfd2d6e64f5176da3631d7af2a30f15a894985759e042a58bc"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
