name = "Debuggy SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "427ef3a278a642f0d59a81cedf0c1450bd8690d7c665b7108de0a088120ab08e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
