name = "Debuggy SMP"
author = "woodiertexas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17f63c4d20fa52b159603ca018dc89eaedfa8131b20602ef0f76d5997d3f6a73"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
