name = "Unofficial Quilt SMP"
author = "woodiertexas"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "471d5776d3eb25375d350a037e1a072bc0c9bbf8e8e10dcdf147dcf455cc67ee"

[versions]
minecraft = "1.20.1"
quilt = "0.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "resources/datapacks"
