# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
globalTooltip: false
noMicrosoftTelemetry: true
debug:
  tagsTooltip: false
  debugTooltipMsg: false
  NBTTooltip: false
suppressExperimentalSettingsWarning: false
